INSERT INTO venueLevel (LEVELID, LEVELNAME, LEVELPRICE, LEVELROW, LEVELSEATSPERROW) VALUES ( 4,'Balcony 2','$100',2,8 );
INSERT INTO venueLevel (LEVELID, LEVELNAME, LEVELPRICE, LEVELROW, LEVELSEATSPERROW) VALUES ( 3,'Balcony 1','$100',2,8 );
INSERT INTO venueLevel (LEVELID, LEVELNAME, LEVELPRICE, LEVELROW, LEVELSEATSPERROW) VALUES ( 2,'Main','$100',2,8 );
INSERT INTO venueLevel (LEVELID, LEVELNAME, LEVELPRICE, LEVELROW, LEVELSEATSPERROW) VALUES ( 1,'Orchestra','$100',2,8 );